/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Logica.InferenciaDifusa;
import Logica.Variable;
import java.util.ArrayList;

/**
 *
 * @author TOSHIBA
 */
public class Experto extends javax.swing.JFrame {

    /**
     * Creates new form Experto
     */
    public Experto() {
        initComponents();
        esconderEntradas();
        listaVariables = new ArrayList();
        //cargar informacion del archivo al modelo listaVariables
        
        //Mostrar las variables cargadas para entrada de datos
        mostrarEntradas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        lblVar1 = new javax.swing.JLabel();
        lblVar2 = new javax.swing.JLabel();
        lblVar3 = new javax.swing.JLabel();
        lblVar4 = new javax.swing.JLabel();
        lblVar5 = new javax.swing.JLabel();
        lblVar6 = new javax.swing.JLabel();
        lblVar7 = new javax.swing.JLabel();
        lblVar8 = new javax.swing.JLabel();
        lblVar9 = new javax.swing.JLabel();
        lblVar10 = new javax.swing.JLabel();
        txtVar1 = new javax.swing.JTextField();
        txtVar2 = new javax.swing.JTextField();
        txtVar3 = new javax.swing.JTextField();
        txtVar4 = new javax.swing.JTextField();
        txtVar5 = new javax.swing.JTextField();
        txtVar6 = new javax.swing.JTextField();
        txtVar7 = new javax.swing.JTextField();
        txtVar8 = new javax.swing.JTextField();
        txtVar9 = new javax.swing.JTextField();
        txtVar10 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Sistema Experto Difuso");

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Entradas");

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("Salida");

        lblVar1.setText("jLabel1");

        lblVar2.setText("jLabel2");

        lblVar3.setText("jLabel3");

        lblVar4.setText("jLabel4");

        lblVar5.setText("jLabel5");

        lblVar6.setText("jLabel6");

        lblVar7.setText("jLabel7");

        lblVar8.setText("jLabel8");

        lblVar9.setText("jLabel9");

        lblVar10.setText("jLabel10");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(320, 320, 320)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(lblVar3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(lblVar2)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(lblVar1)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblVar4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(lblVar5)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblVar6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblVar7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblVar8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblVar9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVar10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtVar10, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(txtVar9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVar8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVar7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVar6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVar5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVar4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVar1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVar2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVar3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(btnProcesar)
                                .addGap(73, 73, 73)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVar1)
                                    .addComponent(txtVar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVar2)
                            .addComponent(txtVar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblVar3))
                    .addComponent(txtVar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtVar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVar5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblVar4)
                                    .addComponent(txtVar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProcesar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVar6)
                        .addGap(18, 18, 18)
                        .addComponent(lblVar7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVar8)
                    .addComponent(txtVar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVar9)
                    .addComponent(txtVar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVar10)
                    .addComponent(txtVar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Boton que inicia la inferencia difusa
     */
    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        //Crear un arreglo con las entradas del usuario
        ArrayList<Double> entradas = new ArrayList();
        
        for (int i=0 ; i<listaVariables.size() ; i++) {
            
            switch(i) {
                case 0:
                    entradas.add(Double.parseDouble(txtVar1.getText()));
                    break;
                case 1:
                    entradas.add(Double.parseDouble(txtVar2.getText()));
                    break;
                case 2:
                    entradas.add(Double.parseDouble(txtVar3.getText()));
                    break;
                case 3:
                    entradas.add(Double.parseDouble(txtVar4.getText()));
                    break;
                case 4:
                    entradas.add(Double.parseDouble(txtVar5.getText()));
                    break;
                case 5:
                    entradas.add(Double.parseDouble(txtVar6.getText()));
                    break;
                case 6:
                    entradas.add(Double.parseDouble(txtVar7.getText()));
                    break;
                case 7:
                    entradas.add(Double.parseDouble(txtVar8.getText()));
                    break;
                case 8:
                    entradas.add(Double.parseDouble(txtVar9.getText()));
                    break;
                case 9:
                    entradas.add(Double.parseDouble(txtVar10.getText()));
                    break;
            }
            
        }
        
        //crear el objeto que realiza el proceso de inferencia difusa
        InferenciaDifusa inferencia = new InferenciaDifusa(listaVariables, entradas);
        Double resultado = inferencia.calcularSalida();
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Experto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Experto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Experto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Experto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Experto().setVisible(true);
            }
        });
    }
    
    public void esconderEntradas() {
        lblVar1.setVisible(false);
        lblVar2.setVisible(false);
        lblVar3.setVisible(false);
        lblVar4.setVisible(false);
        lblVar5.setVisible(false);
        lblVar6.setVisible(false);
        lblVar7.setVisible(false);
        lblVar8.setVisible(false);
        lblVar9.setVisible(false);
        lblVar10.setVisible(false);
        
        txtVar1.setVisible(false);
        txtVar2.setVisible(false);
        txtVar3.setVisible(false);
        txtVar4.setVisible(false);
        txtVar5.setVisible(false);
        txtVar6.setVisible(false);
        txtVar7.setVisible(false);
        txtVar8.setVisible(false);
        txtVar9.setVisible(false);
        txtVar10.setVisible(false);
    }
    
    public void mostrarEntradas() {
        for (int i=0 ; i<listaVariables.size() ; i++) {
            
            switch(i) {
                case 0:
                    lblVar1.setText(listaVariables.get(i).getNombre());
                    lblVar1.setVisible(true);
                    txtVar1.setVisible(true);
                    break;
                case 1:
                    lblVar2.setText(listaVariables.get(i).getNombre());
                    lblVar2.setVisible(true);
                    txtVar2.setVisible(true);
                    break;
                case 2:
                    lblVar3.setText(listaVariables.get(i).getNombre());
                    lblVar3.setVisible(true);
                    txtVar3.setVisible(true);
                    break;
                case 3:
                    lblVar4.setText(listaVariables.get(i).getNombre());
                    lblVar4.setVisible(true);
                    txtVar4.setVisible(true);
                    break;
                case 4:
                    lblVar5.setText(listaVariables.get(i).getNombre());
                    lblVar5.setVisible(true);
                    txtVar5.setVisible(true);
                    break;
                case 5:
                    lblVar6.setText(listaVariables.get(i).getNombre());
                    lblVar6.setVisible(true);
                    txtVar6.setVisible(true);
                    break;
                case 6:
                    lblVar7.setText(listaVariables.get(i).getNombre());
                    lblVar7.setVisible(true);
                    txtVar7.setVisible(true);
                    break;
                case 7:
                    lblVar8.setText(listaVariables.get(i).getNombre());
                    lblVar8.setVisible(true);
                    txtVar8.setVisible(true);
                    break;
                case 8:
                    lblVar9.setText(listaVariables.get(i).getNombre());
                    lblVar9.setVisible(true);
                    txtVar9.setVisible(true);
                    break;
                case 9:
                    lblVar10.setText(listaVariables.get(i).getNombre());
                    lblVar10.setVisible(true);
                    txtVar10.setVisible(true);
                    break;
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel lblVar1;
    private javax.swing.JLabel lblVar10;
    private javax.swing.JLabel lblVar2;
    private javax.swing.JLabel lblVar3;
    private javax.swing.JLabel lblVar4;
    private javax.swing.JLabel lblVar5;
    private javax.swing.JLabel lblVar6;
    private javax.swing.JLabel lblVar7;
    private javax.swing.JLabel lblVar8;
    private javax.swing.JLabel lblVar9;
    private javax.swing.JTextField txtVar1;
    private javax.swing.JTextField txtVar10;
    private javax.swing.JTextField txtVar2;
    private javax.swing.JTextField txtVar3;
    private javax.swing.JTextField txtVar4;
    private javax.swing.JTextField txtVar5;
    private javax.swing.JTextField txtVar6;
    private javax.swing.JTextField txtVar7;
    private javax.swing.JTextField txtVar8;
    private javax.swing.JTextField txtVar9;
    // End of variables declaration//GEN-END:variables

    public ArrayList<Variable> listaVariables;

}
